- hosts: web
  become: yes

  vars:
    - system_php: 7.2
    - secondary_php:
        php56: false
        php70: true
        php71: false
        php72: false
        php73: false
        php74: false
        php80: false

  roles:
  - { role : php }
