- hosts: web
  become: yes

  vars:
    - site_user_name: "example"
    - site_name: "example.com"
    - db_name: "test"
    - db_user: "test"
    - db_pass: "test"

  roles:
  - { role : common }
  - { role : nginx }
  - { role : mysql }
  - { role : php }
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
