php56_packages:
  - php56-php
  - php56-php-bcmath
  - php56-php-cli
  - php56-php-common
  - php56-php-fpm
  - php56-php-intl
  - php56-php-json
  - php56-php-mbstring
  - php56-php-mysqlnd
  - php56-php-odbc
  - php56-php-opcache
  - php56-php-pdo
  - php56-php-pear.noarch
  - php56-php-pecl-apcu
  - php56-php-pecl-zip
  - php56-php-process
  - php56-php-soap
  - php56-php-xml
