php73_packages:
  - php73-php
  - php73-php-bcmath
  - php73-php-cli
  - php73-php-common
  - php73-php-fpm
  - php73-php-gd
  - php73-php-intl
  - php73-php-json
  - php73-php-mbstring
  - php73-php-mysqlnd
  - php73-php-odbc
  - php73-php-opcache
  - php73-php-pdo
  - php73-php-pear.noarch
  - php73-php-pecl-apcu
  - php73-php-pecl-zip
  - php73-php-process
  - php73-php-soap
  - php73-php-xml
