php74_packages:
  - php74-php
  - php74-php-bcmath
  - php74-php-cli
  - php74-php-common
  - php74-php-fpm
  - php74-php-gd
  - php74-php-intl
  - php74-php-json
  - php74-php-mbstring
  - php74-php-mysqlnd
  - php74-php-odbc
  - php74-php-opcache
  - php74-php-pdo
  - php74-php-pear.noarch
  - php74-php-pecl-apcu
  - php74-php-pecl-zip
  - php74-php-process
  - php74-php-soap
  - php74-php-xml
