php80_packages:
  - php80-php
  - php80-php-bcmath
  - php80-php-cli
  - php80-php-common
  - php80-php-fpm
  - php80-php-gd
  - php80-php-intl
  - php80-php-json
  - php80-php-mbstring
  - php80-php-mysqlnd
  - php80-php-odbc
  - php80-php-opcache
  - php80-php-pdo
  - php80-php-pear.noarch
  - php80-php-pecl-apcu
  - php80-php-pecl-zip
  - php80-php-process
  - php80-php-soap
  - php80-php-xml
