- name: Installing Remo repo 
  command: dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
  args:  
    warn: no
    creates: /etc/yum.repos.d/remi-safe.repo

- name: Checking Remo repo
  shell:
    cmd: dnf -C repolist enabled -v  | grep '^Repo-id' | awk '$3 == "remi-safe" {print "enabled"}'
    warn: false 
  check_mode: no
  changed_when: false
  register: remi_repo

- import_tasks: clean_php.yml
  when: system_php_reinstall or secondary_php_reinstall

- name: Choose PHP REMI Repo
  shell: |
    dnf module enable -y "php:remi-{{ system_php }}"
  check_mode: no
  changed_when: false
  args:  
    warn: false
  when: remi_repo.stdout == 'enabled'


- name: Installing System PHP
  dnf:
    name: "{{ php_packages }}"
    state: latest


- import_tasks: secondary_php.yml
  when: secondary_php['php56'] or secondary_php['php70'] or secondary_php['php71'] or secondary_php['php72'] or secondary_php['php73'] or secondary_php['php74'] or secondary_php['php80']
